name: Deploy to PyPI

on:
  push:
    branches:
      - pypi

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./  # Adjust the working directory if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Use actions/setup-node instead of actions/setup-python
        with:
          node-version: 16  # Specify Node.js version

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build and publish
        run: |
          python setup.py sdist bdist_wheel
          python -m twine upload --skip-existing --repository-url https://upload.pypi.org/legacy/ dist/*

        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}